name: Sync Predictions

on:
  push:
    paths:
      - 'nba_predictions.csv'
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          path: nba-predictor

      - name: Checkout destination repo
        uses: actions/checkout@v4
        with:
          repository: wmjs/wmjs.github.io
          token: ${{ secrets.SYNC_PAT }}
          path: wmjs.github.io

      - name: Copy predictions file
        run: |
          ls
          cp nba-predictor/nba_display.csv wmjs.github.io/nba_page
          cd wmjs.github.io
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "GitHub Actions Bot"
            git config user.email "actions@github.com"
            git add nba_page/nba_display.csv
            git commit -m "Update NBA predictions"
            git push
          fi 
